print('Mo said "What are you doing" ')
print('I said \"Writing python code\" ')
print('Mo said \"Can you upload\" ')
print('I said \"Upload what\" ')
print('Mo said \"Nevermind, forget that\" ')
print('I said \"Forgot what\" ')
print('Mo said \"Come on stop playing this game man\" ')
print('I said \"What game\" ')
print('Mo said \"Whatever man, this is so annoying\" ')
print('I said \"Ok bye\" ')
